<?php
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://www.starludoplayers.com/run-cron',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'Cookie: XSRF-TOKEN=eyJpdiI6InBDYUszbTlFTDVpWFQ5QmFQZzRMWmc9PSIsInZhbHVlIjoidE5aTXhYRXcyOVRKL3FRaitNaG4wM3ZYbkg3a2JhbVBHQUp5SEtJRGorMWJPSUh5RjlBMHNZeXBjWm54aVNJSlZ3eGdsK2ZZd2thMmhUR25zUXpRQnpydHIyTklTVmdoN1ltYU5xR2h3aHlLWk0xRVhUYlFnOHc2SVdVemgxYUQiLCJtYWMiOiI5YzkzNmZiNjI2YzE1YjQ1Zjc2OWNkOGI0ZTAwNDEzZDc1ZDNmNDIwZWU0NTc4MGJmNDczZDY3YThkNDM0NjI3IiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6InhYOWtIWHFqdjgwaTNZVk5hdkJqYkE9PSIsInZhbHVlIjoiVWUwSXNxU056VGFybTRVRlRjaUxONllscmRRY2tXWUFTUlBWMW9QT200cnZZZ01TNk4yOVJuSEZyWGQ1enlSdVJDdEN1b0dIbWEvSzVyY2FLZW1BY1lSc0pLRktiWDc1S1hsR2dBa0JtajZ1eHVnRXpHdUprcXBKTWdHQzZVTTMiLCJtYWMiOiJmMjM4MzFiMzM0MzhkZThkNTczZmFhZjg4YmViYWRiY2ZmM2JkOTJlNTkzY2U0ZDI4ODdjNDdkYjVlMGU3MjBkIiwidGFnIjoiIn0%3D'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;